### ISSUE TITLE
v1.0.14 Crashes When Changing Room

### ISSUE THREAD

**Issue by JonathanHackerCG** [nommiin/ImGui_GM#11]
ImGui_GM v1.0.14
IDE v2023.8.2.108
Runtime v2023.8.2.152

Crash message:
![image](https://github.com/nommiin/ImGui_GM/assets/49505360/40e956e7-5e59-4005-9003-a8c28d7e589c)

Reproduction:
1) Follow the setup steps in the readme in a blank project.
2) Add another room to the project.
3) Call `room_goto` to change rooms.

I believe this also happens on `game_restart` and `game_end` but did not double check.
v1.0.13 works as expected.

YYZ attached in the .zip.
[ImGui_GM Bug Report.zip](https://github.com/nommiin/ImGui_GM/files/13260208/ImGui_GM.Bug.Report.zip)

**Comment by nommiin** [comment]
So, bit of a mistake on my part! I accidentally included the debug DLL as the main DLL being loaded by the extension. This error is actually intended behaviour, but just wasn't displaying before as the release DLL was included in all the prior packages

This error does bring a good point to light though, and it's the fact that calling functions like `room_goto` or `game_restart` prevent the draw events on some objects from being called. Because of this, often times calling these functions will prevent `ImGui.__Render` from being called and finishing the frame... so I've went ahead and wrapped the `ImGui::EndFrame()` function. This function is normally called by `ImGui.__Render` for you, but since that code isn't ran... we need to do it manually.

Fortunately, as per-suggestion from Juju; you can call this function in the "Room End" event and that will take care of everything for you! It's a pretty graceful solution, and v1.0.15 now includes `ImGui.EndFrame`. I've also updated the example project to handle this logic as well.

Let me know if this issue comes up any further though, thanks for bringing this to my attention as well!
